from typing import Any, Optional

from minorm.db_specs import BaseSpec


class ConnectorError(RuntimeError): ...

class Connector:
    NOT_CONNECTED_ERROR: str = ...
    _connection: Optional[Any] = ...
    _db_spec: Optional[BaseSpec] = ...
    _autocommit: Optional[bool] = ...
    def __init__(self) -> None: ...
    def connect(self, db_spec: BaseSpec) -> 'Connector': ...
    def disconnect(self) -> None: ...
    def set_autocommit(self, autocommit: bool) -> None: ...
    @property
    def spec(self) -> BaseSpec: ...
    @property
    def connection(self) -> Any: ...
    def cursor(self) -> None: ...
    def _check_if_connected(self) -> None: ...

connector: Connector
